# Generated by Django 4.2 on 2025-12-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundryshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryservice',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laundry_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
